[package]
name = "spotify_info"
version = "0.1.0"
edition = "2021"
authors = ["Ricky12Awesome"]
description = "Gets metadata from spotify using a spicetify extension using websockets"
readme = "README.md"
license = "MIT"
repository = "https://github.com/Ricky12Awesome/spotify_info"
homepage = "https://github.com/Ricky12Awesome/spotify_info"
exclude = ["extension", "test_bin"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.16.0"